cmake_minimum_required(VERSION 3.10)
project(ex10_02)
add_executable(${PROJECT_NAME} ex10_02.cpp)
add_library(mypolylib STATIC src/polyline.cpp)
target_link_libraries(${PROJECT_NAME} mypolylib)
target_include_directories(${PROJECT_NAME} PRIVATE include)
target_include_directories(mypolylib PRIVATE include)